### PR TITLE
Attach JS rename handler to mobile menu items.

### LINKED ISSUE #150: Rename Page button doesn't work
it sends me to the current page + '?do=menuitem', producing an error, "Action unknown: menuitem"

### LINKED ISSUE #169: Can't update pagename, or move files
when i try to update a name of a files i get"Action unknown: menuitem"

I can't move file or repo as well "a deplacement didn't proced to its end - use these buttons to keep going or abandon" (its badly translated).

do you have any ideas on what is going wrong ? (i use CKGedit as editor, material design as template and 2018-04-22a "Greebo" as version of dokuwiki)

### PR DESCRIPTION
**Pull request by splitbrain**
When the MobileMenu is used the required handler to show the rename
dialog wasn't attached to the select resulting in an unkown action
call.

This attaches the handler and uses a jQuery specific trick to be the
first handler to be evaluated (allowing to cancel the default handler
used on the quickselect behaviour).

fixes #150
fixes #169

### CODE REVIEW

File: MenuItem.php [hunk 1]
```diff
@@ -13,6 +13,8 @@ class MenuItem extends AbstractItem {
     /** @var string icon file */
     protected $svg = __DIR__ . '/images/rename.svg';
 
+    protected $type = "plugin_move_page";
```
Comment (michitux) [inline MenuItem.php:16]: This completely breaks displaying the non-mobile rename menu item:

Screenshot 2022-01-24-move-link

I think this is because the plugin still contains some CSS for the menu item produced by `TEMPLATE_PAGETOOLS_DISPLAY` that is still handled in the plugin and due to this change, this CSS is now applied to the new menu item. I don't know if there are still templates for which this event and the corresponding CSS is relevant.

File: script/rename.js [hunk 2]
```diff
@@ -3,81 +3,125 @@
...
+    // attach handler to menu item
+    jQuery('.plugin_move_page')
+        .show()
+        .click(function (e) {
+            e.preventDefault();
+            showDialog();
+        });
+
+    // attach handler to mobile menu entry
+    $mobileMenuOption = jQuery('form select[name=do] option[value=plugin_move_page]');
```
Comment (michitux) [inline script/rename.js:116]:
```suggestion
    const $mobileMenuOption = jQuery('form select[name=do] option[value=plugin_move_page]');
```
The variable should be declared.

**Review by michitux — CHANGES_REQUESTED** [review]
Thank you very much, apart from the two comments this looks good. I would have implemented this differently by actually implementing a non-JS rename action as this popup dialog is also not very mobile-friendly but this definitely fixes the problem and that's what counts here.

I noticed another minor issue: if you click cancel in the dialog, the select stays at the rename page option and you cannot re-trigger the rename page option without triggering another option before. As it's a really minor issue feel free to ignore this, though, as I'm not sure this can be easily fixed and I do not want this to be the reason why we cannot just fix this long-standing bug.

File: script/rename.js (hunk 2 above)
Comment (splitbrain) [reply script/rename.js]: fixed

File: MenuItem.php (hunk 1 above)
Comment (splitbrain) [reply MenuItem.php]: ah, yes these old styles clashed. The handling for that event should be removed, but for now I simply renamed the class.

**Comment by splitbrain** [comment]
I went for the JavaScript version here because the mobile menu is also used on desktop in many CMS-like templates... but yeah the popup could use some more love for mobile devices... the dropdown is now reset on selection.

**Review by michitux — APPROVED** [review]
